node{
    def extractreport = '(cd ./static && tar xvjf ../qmstr-reports.tar.bz2 && mv ./reports ./packages)'
    def extractdocs = '(cd ./static && tar xvjf ../qmstr-doc.tar.bz2)'

    try{

        parameters {
            string(name: 'project', defaultValue: 'nil', description: 'Project name that triggers web publisher')
            }
        stage('Clone sources') {
            cleanWs()
            git url: 'https://github.com/senaingrid/test-web'
            echo "Copying artifacts from last successful build from DOCS job"
            copyArtifacts fingerprintArtifacts: true,  flatten: true, projectName: 'QMSTR-intern/WIP_docs-build', selector: upstream(fallbackToLastSuccessful: true)
            // extractreport = ("${params.project}" == 'docs') ? 'echo "No report to extract."' : extractreport
            echo "Copying artifacts from last successful build from ${params.project} job"
            if ("${params.project}" == 'curl') {
                copyArtifacts fingerprintArtifacts: true,  flatten: true, projectName: 'QMSTR/qmstr-cURL-demo', selector: upstream(fallbackToLastSuccessful: true)
            } else if ("${params.project}" == 'jabref') {
                copyArtifacts fingerprintArtifacts: true,  flatten: true, projectName: 'QMSTR/qmstr-jabref-demo', selector: upstream(fallbackToLastSuccessful: true)
            }
        }
        stage('publish website'){
            withEnv(["PATH+SNAP=/snap/bin"]){
                echo "Publishing QMSTR site with ${params.project} project"
                sh 'git submodule init && git submodule update'
                sh "${extractdocs}"
                sh "${extractreport}"
                sh './scripts/generate-data-branch.sh ./web_data_dir'
                sh 'git config http.sslVersion tlsv1.2'
                sh 'git push --force https://try56985236655563:E5a!ftrg@github.com/senaingrid/test-web gh-pages'
                }
            }
        }
    catch (Exception e)
    {
        currentBuild.result = 'FAILURE'
        if (currentBuild.getPreviousBuild().result != 'FAILURE') {
        }
    }
}
